---
# tasks file for springboot_apps

- include: prepare.yml

#- name: Download Spring Boot fat jar from Nexus repository
#  get_url:
#    url: "{{ app_acb_nexus_url }}?r={{ app_acb_repository }}&g={{ app_acb_groupid }}&a={{ app_acb_artifactid }}&v={{ app_acb_version }}&p={{ app_acb_package }}"
#    dest: "{{ app_acb_jar_dir }}/{{ app_acb_jar_name }}"
#    owner: "{{ app_acb_owner }}"
#    group: "{{ app_acb_group }}"
#    force: yes
#    mode: 0755

- name: Copy Spring Boot application configuration directory
  template:
    src: application.properties.j2
    dest: "{{ app_acb_config_dir }}/application.properties"
    owner: "{{ app_acb_owner }}"
    group: "{{ app_acb_group }}"
    mode: 0750

- name: Install systemd service
  template:
    src: app_acb.service.j2
    dest: "/etc/systemd/system/{{ app_acb_service_name }}.service"
    owner: root
    group: root
    mode: 0644

- name: Reload service configuration.
  command: >
    systemctl daemon-reload

- name: Enable and Launch service
  systemd:
    state: started
    name: "{{ app_acb_service_name }}"
    enabled: yes

- name: Add Iptables rule
  include: iptables.yml