---
- name: install unzip
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "unzip"
    - "tar"

- name: create user's group for the app
  group:
    name: "{{ app_group }}"
    system: yes

- name: create user for the app
  user:
    createhome: no
    group: "{{ app_acb_group }}"
    name: "{{ app_acb_owner }}"
    shell: /sbin/nologin
    system: yes

- name: Create directories for the app
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_acb_owner }}"
    group: "{{ app_acb_group }}"
    recurse: yes
  with_items:
    - "{{ app_acb_config_dir }}"
    - "{{ app_acb_jar_dir }}"
    - "{{ app_acb_files_dir }}"
    - "{{ app_acb_log_dir }}"