---
# tasks file for postgres

- name: Installing PostgreSQL Server packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ postgres_server_pkg }}"
    - "{{ postgres_client_pkg }}"
    - "python-psycopg2"

- name: Create user
  postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_user_password }}"
    role_attr_flags: "{{ postgres_user_role }}"
    state: present
  with_items: "{{ postgres_instance_dbs }}"

- name: Create database
  postgresql_db:
    name: "{{ postgres_database }}"
    owner: "{{ postgres_user }}"
    state: present

- name: Create schema
  postgresql_schema:
    database: "{{ postgres_database }}"
    name: "{{ posgres_schema }}"
    owner: "{{ postgres_user }}"
    state: present