---
# defaults file for postgres
postgres_port: 5432
postgres_version: 9.6
postgres_server_pkg: "postgresql-{{postgres_version}}"
postgres_client_pkg: "postgresql-client-{{postgres_version}}"
postgres_conf_dir: "/etc/postgresql/{{postgres_version}}/main"
postgres_pg_hba_file: "{{ postgres_conf_dir }}/pg_hba.conf"
postgres_user:
postgres_user_password:
postgres_user_role:
postgres_database:
posgres_schema:
