---

###################
# Securite
###################
- hosts: all
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: firewall, tags: ['firewall'] }

# ###################
# Base de données
# ###################
- hosts: database
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: postgres, tags: ['postgres'] }

# ###################
# Application Spring Boot
# ###################
- hosts: springboot
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
     - { role: openjdk8, tags: ['openjdk8'] }
     - { role: app_acb, app_acb_db_user: "{{ postgres_user }}", app_acb_db_user_password: "{{ postgres_user_password }}",app_acb_db_database: "{{ postgres_database }}",app_acb_db_schema: "{{ posgres_schema }}", tags: ['app_acb'] }